name: Set up WireGuard
description: Creates a new WireGuard config names "github-actions" and launches WireGuard with it

inputs:
  config:
    description: "WireGuard configuration"
    required: true

runs:
  using: composite
  steps:
    - name: Install WireGuard and wg-quick
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y wireguard wireguard-tools

    - name: Dump the configuration into a file
      shell: bash
      run: sudo echo "$WG_CONFIG" > /etc/wireguard/github-actions.conf
      env:
        WG_CONFIG: ${{ inputs.config }}

    - name: Bring up the WireGuard interface
      shell: bash
      run: sudo wg-quick up github-actions
