name: Set up WireGuard
description: Creates a new WireGuard config at "../github-actions.conf" and launches WireGuard with it

inputs:
  config:
    description: "WireGuard configuration"
    required: true

runs:
  using: composite
  steps:
    - name: Install WireGuard and wg-quick
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y wireguard wireguard-tools

    - name: Dump the configuration into a file
      shell: bash
      run: echo "$WG_CONFIG" > ../github-actions.conf
      env:
        WG_CONFIG: ${{ inputs.config }}

    - name: Bring up the WireGuard interface
      shell: bash
      run: sudo wg-quick up ../github-actions.conf

    - name: Test the connection
      id: test-connection
      shell: bash
      run: ping -c 4 one.one.one.one
      continue-on-error: true

    - name: Restart WireGuard if the connection test failed
      if: steps.test-connection.outcome == 'failure'
      shell: bash
      run: |
        echo "Connection test failed, restarting WireGuard..."
        sudo wg-quick down ../github-actions.conf
        sudo wg-quick up ../github-actions.conf

    - name: Verify the connection again
      shell: bash
      run: ping -c 4 one.one.one.one
