_id: 68c1829c97e35341c408a955
appOnly: false
brand: NZA
brands:
  - id: af9c3dc4-d31b-56fb-b5c3-1cd10c2de9dd
    name: NZA
categories:
  - 5e128d76-49a0-57be-94c2-7fbd88e59284
classicId: '2755196'
classicProductId: '585528'
deliveryPrice:
  cents: 595
  currency: EUR
  value: 5.95
directCheckout: true
discount: 85
end: '2025-09-15T21:59:59.999Z'
freeDelivery: false
id: c230bb88-2e46-4140-bd02-b33692b8310d
logo:
  channels:
    - website
    - app
    - newsletter
  extension: png
  id: 1634994
  priority: 100
  slug: nza-logo
  type: logo
offerId: b026156c-18e6-46cc-b9ee-f3f972305c34
price:
  cents: 1500
  currency: EUR
  value: 15
referencePrice:
  cents: 9995
  currency: EUR
  value: 99.95
slug: productdetails-voorbeeld
soldOut: true
start: '2025-09-09T22:00:00.000Z'
title: Producttitel hier
