name: Archive

on:
  schedule:
    - cron: "0 1 * * *" # every day at 01:00
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2

      - uses: ./.github/actions/set-up-wireguard
        with:
          config: ${{ secrets.WIREGUARD_CONFIG }}

      - run: bun index.ts
        env:
          IBEX_LANGUAGE: nl
          IBEX_TENANT_ID: ${{ vars.IBEX_TENANT_ID }}
          IBEX_SHOP_ID: ${{ vars.IBEX_SHOP_ID }}
          USER_AGENT: ${{ vars.USER_AGENT }}
          SEC_CH_UA: '${{ vars.SEC_CH_UA }}'

      - uses: ./.github/actions/tear-down-wireguard

      - name: Commit changes with the number of files in products/ as the commit message
        run: |
          git config --local user.email "👉@👈"
          git config --local user.name "Archiver"
          git add -A
          git commit -m "$(date +'%Y-%m-%d') - $(ls -l products | wc -l) files"
          git push
